# -*- coding: utf-8 -*-
# @Time    : 2020/5/26 0026 20:10
# @Author  : X.H
from flask_sqlalchemy import SQLAlchemy

db = SQLAlchemy()


class Sequential(db.Model):
    __tablename__ = 'sequential'
    id = db.Column(db.INTEGER, primary_key=True, autoincrement=True)
    # 个人编号 1-2977
    number = db.Column(db.INTEGER)
    value1 = db.Column(db.FLOAT)
    value2 = db.Column(db.FLOAT)
    value3 = db.Column(db.FLOAT)
    value4 = db.Column(db.FLOAT)
    value5 = db.Column(db.FLOAT)
    value6 = db.Column(db.FLOAT)
    value7 = db.Column(db.FLOAT)
    value8 = db.Column(db.FLOAT)
    value9 = db.Column(db.FLOAT)
    value10 = db.Column(db.FLOAT)
    value11 = db.Column(db.FLOAT)
    value12 = db.Column(db.FLOAT)
    value13 = db.Column(db.FLOAT)
    value14 = db.Column(db.FLOAT)
    value15 = db.Column(db.FLOAT)
    value16 = db.Column(db.FLOAT)
    value17 = db.Column(db.FLOAT)
    value18 = db.Column(db.FLOAT)
    value19 = db.Column(db.FLOAT)
    value20 = db.Column(db.FLOAT)
    value21 = db.Column(db.FLOAT)
    value22 = db.Column(db.FLOAT)
    value23 = db.Column(db.FLOAT)
    value24 = db.Column(db.FLOAT)
    value25 = db.Column(db.FLOAT)
    value26 = db.Column(db.FLOAT)
    value27 = db.Column(db.FLOAT)
    value28 = db.Column(db.FLOAT)
    value29 = db.Column(db.FLOAT)
    value30 = db.Column(db.FLOAT)
    value31 = db.Column(db.FLOAT)
    value32 = db.Column(db.FLOAT)
    value33 = db.Column(db.FLOAT)
    value34 = db.Column(db.FLOAT)
    value35 = db.Column(db.FLOAT)
    value36 = db.Column(db.FLOAT)
    value37 = db.Column(db.FLOAT)
    value38 = db.Column(db.FLOAT)
    value39 = db.Column(db.FLOAT)
    value40 = db.Column(db.FLOAT)
    value41 = db.Column(db.FLOAT)
    value42 = db.Column(db.FLOAT)
    value43 = db.Column(db.FLOAT)
    value44 = db.Column(db.FLOAT)
    value45 = db.Column(db.FLOAT)
    value46 = db.Column(db.FLOAT)
    value47 = db.Column(db.FLOAT)
    value48 = db.Column(db.FLOAT)
    value49 = db.Column(db.FLOAT)
    value50 = db.Column(db.FLOAT)


class Clinical(db.Model):
    __tablename__ = 'clinical'
    number = db.Column(db.INTEGER,primary_key=True)
    SEQN = db.Column(db.String(255))
    mortstat = db.Column(db.String(255))
    SDDSRVYR = db.Column(db.String(255))
    permth_exm = db.Column(db.String(255))
    permth_int = db.Column(db.String(255))
    ucod_leading = db.Column(db.String(255))
    diabetes_mcod = db.Column(db.String(255))
    hyperten_mcod = db.Column(db.String(255))
    SDMVPSU = db.Column(db.String(255))
    SDMVSTRA = db.Column(db.String(255))
    WTINT2YR = db.Column(db.String(255))
    WTMEC2YR = db.Column(db.String(255))
    RIDAGEMN = db.Column(db.String(255))
    RIDAGEEX = db.Column(db.String(255))
    RIDAGEYR= db.Column(db.String(255))
    BMI = db.Column(db.String(255))
    BMI_cat = db.Column(db.String(255))
    Race = db.Column(db.String(255))
    Gender = db.Column(db.String(255))
    Diabetes = db.Column(db.String(255))
    CHF = db.Column(db.String(255))
    CHD = db.Column(db.String(255))
    Cancer = db.Column(db.String(255))
    Stroke = db.Column(db.String(255))
    EducationAdult = db.Column(db.String(255))
    MobilityProblem = db.Column(db.String(255))
    DrinkStatus = db.Column(db.String(255))
    DrinksPerWeek = db.Column(db.String(255))
    SmokeCigs = db.Column(db.String(255))
    BPXSY1 = db.Column(db.String(255))
    BPXSY2 = db.Column(db.String(255))
    BPXSY3 = db.Column(db.String(255))
    BPXSY4 = db.Column(db.String(255))
    LBXTC = db.Column(db.String(255))
    LBDHDD = db.Column(db.String(255))
    mort = db.Column(db.String(255))
    Age = db.Column(db.String(255))
    SYS = db.Column(db.String(255))
    TAC = db.Column(db.String(255))
    TLAC = db.Column(db.String(255))
    TLAC_1 = db.Column(db.String(255))
    TLAC_2 = db.Column(db.String(255))
    TLAC_3 = db.Column(db.String(255))
    TLAC_4 = db.Column(db.String(255))
    TLAC_5 = db.Column(db.String(255))
    TLAC_6 = db.Column(db.String(255))
    TLAC_7 = db.Column(db.String(255))
    TLAC_8 = db.Column(db.String(255))
    TLAC_9 = db.Column(db.String(255))
    TLAC_10 = db.Column(db.String(255))
    TLAC_11 = db.Column(db.String(255))
    TLAC_12 = db.Column(db.String(255))








